# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Lint with flake8
      run: |
        pip install -U pip
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./python --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./python --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Installing ngen_conf in python virtual environment
      run: |
        # setup virtual environment
        python -m venv venv
        source ./venv/bin/activate
        pip install "python/ngen_conf[develop]"

    - name: Testing ngen_conf with pytest
      run: |
        source ./venv/bin/activate
        pytest python/ngen_conf

    - name: Cleaning up python virtual environment
      run: |
        # cleanup virtual environment
        rm -rf venv

    - name: Installing ngen_cal in python virtual environment
      run: |
        # setup virtual environment
        python -m venv venv
        source ./venv/bin/activate
        pip install "python/ngen_cal[develop]"
        # NOTE: Install checked out version of ngen_conf.
        # This ensure ngen_cal tests test against ngen_conf source checked out by the runner.
        pip install python/ngen_conf

    - name: Testing ngen_cal with pytest
      run: |
        source ./venv/bin/activate
        pytest python/ngen_cal
